name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - main
      
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 📂 Checkout repository
      uses: actions/checkout@master
    - name: Checkout source
      run : |
        git fetch
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - uses: Bogdanp/setup-racket@v1.5
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '8.1'
        packages: 'pollen, gregor, sugar, txexpr' # must be a comma-separated string!
    - run: raco pollen render
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: build # The branch the action should deploy to.
        folder: . # The folder the action should deploy.